package com.caochf.entity;

import java.io.Serializable;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


@Table(name = "OD_SYSTEM_SURVEY")
@ApiModel(value = "OdSystemSurvey",description = "D. 字典")
public class OdSystemSurvey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.ID
     *
     * @mbg.generated
     */
    @Id
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.SYSTEM_NAME
     *
     * @mbg.generated
     */
    private String systemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.SYSTEM_ADDR
     *
     * @mbg.generated
     */
    private String systemAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.SYSTEM_STATUS
     *
     * @mbg.generated
     */
    private String systemStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.SYSTEM_CONTRACTOR
     *
     * @mbg.generated
     */
    private String systemContractor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.INCHARGE_MAN
     *
     * @mbg.generated
     */
    private String inchargeMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.INCHARGE_TEL
     *
     * @mbg.generated
     */
    private String inchargeTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.MANAGER_DEPT
     *
     * @mbg.generated
     */
    private String managerDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.MANAGER_NAME
     *
     * @mbg.generated
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.MANAGER_TEL
     *
     * @mbg.generated
     */
    private String managerTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.DATA_STATUS
     *
     * @mbg.generated
     */
    private String dataStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_system_survey.SYSTEM_INTRODUCTION
     *
     * @mbg.generated
     */
    private String systemIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table od_system_survey
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.ID
     *
     * @return the value of od_system_survey.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.ID
     *
     * @param id the value for od_system_survey.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.SYSTEM_NAME
     *
     * @return the value of od_system_survey.SYSTEM_NAME
     *
     * @mbg.generated
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.SYSTEM_NAME
     *
     * @param systemName the value for od_system_survey.SYSTEM_NAME
     *
     * @mbg.generated
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName == null ? null : systemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.SYSTEM_ADDR
     *
     * @return the value of od_system_survey.SYSTEM_ADDR
     *
     * @mbg.generated
     */
    public String getSystemAddr() {
        return systemAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.SYSTEM_ADDR
     *
     * @param systemAddr the value for od_system_survey.SYSTEM_ADDR
     *
     * @mbg.generated
     */
    public void setSystemAddr(String systemAddr) {
        this.systemAddr = systemAddr == null ? null : systemAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.SYSTEM_STATUS
     *
     * @return the value of od_system_survey.SYSTEM_STATUS
     *
     * @mbg.generated
     */
    public String getSystemStatus() {
        return systemStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.SYSTEM_STATUS
     *
     * @param systemStatus the value for od_system_survey.SYSTEM_STATUS
     *
     * @mbg.generated
     */
    public void setSystemStatus(String systemStatus) {
        this.systemStatus = systemStatus == null ? null : systemStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.SYSTEM_CONTRACTOR
     *
     * @return the value of od_system_survey.SYSTEM_CONTRACTOR
     *
     * @mbg.generated
     */
    public String getSystemContractor() {
        return systemContractor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.SYSTEM_CONTRACTOR
     *
     * @param systemContractor the value for od_system_survey.SYSTEM_CONTRACTOR
     *
     * @mbg.generated
     */
    public void setSystemContractor(String systemContractor) {
        this.systemContractor = systemContractor == null ? null : systemContractor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.INCHARGE_MAN
     *
     * @return the value of od_system_survey.INCHARGE_MAN
     *
     * @mbg.generated
     */
    public String getInchargeMan() {
        return inchargeMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.INCHARGE_MAN
     *
     * @param inchargeMan the value for od_system_survey.INCHARGE_MAN
     *
     * @mbg.generated
     */
    public void setInchargeMan(String inchargeMan) {
        this.inchargeMan = inchargeMan == null ? null : inchargeMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.INCHARGE_TEL
     *
     * @return the value of od_system_survey.INCHARGE_TEL
     *
     * @mbg.generated
     */
    public String getInchargeTel() {
        return inchargeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.INCHARGE_TEL
     *
     * @param inchargeTel the value for od_system_survey.INCHARGE_TEL
     *
     * @mbg.generated
     */
    public void setInchargeTel(String inchargeTel) {
        this.inchargeTel = inchargeTel == null ? null : inchargeTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.MANAGER_DEPT
     *
     * @return the value of od_system_survey.MANAGER_DEPT
     *
     * @mbg.generated
     */
    public String getManagerDept() {
        return managerDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.MANAGER_DEPT
     *
     * @param managerDept the value for od_system_survey.MANAGER_DEPT
     *
     * @mbg.generated
     */
    public void setManagerDept(String managerDept) {
        this.managerDept = managerDept == null ? null : managerDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.MANAGER_NAME
     *
     * @return the value of od_system_survey.MANAGER_NAME
     *
     * @mbg.generated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.MANAGER_NAME
     *
     * @param managerName the value for od_system_survey.MANAGER_NAME
     *
     * @mbg.generated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.MANAGER_TEL
     *
     * @return the value of od_system_survey.MANAGER_TEL
     *
     * @mbg.generated
     */
    public String getManagerTel() {
        return managerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.MANAGER_TEL
     *
     * @param managerTel the value for od_system_survey.MANAGER_TEL
     *
     * @mbg.generated
     */
    public void setManagerTel(String managerTel) {
        this.managerTel = managerTel == null ? null : managerTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.DATA_STATUS
     *
     * @return the value of od_system_survey.DATA_STATUS
     *
     * @mbg.generated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.DATA_STATUS
     *
     * @param dataStatus the value for od_system_survey.DATA_STATUS
     *
     * @mbg.generated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_system_survey.SYSTEM_INTRODUCTION
     *
     * @return the value of od_system_survey.SYSTEM_INTRODUCTION
     *
     * @mbg.generated
     */
    public String getSystemIntroduction() {
        return systemIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_system_survey.SYSTEM_INTRODUCTION
     *
     * @param systemIntroduction the value for od_system_survey.SYSTEM_INTRODUCTION
     *
     * @mbg.generated
     */
    public void setSystemIntroduction(String systemIntroduction) {
        this.systemIntroduction = systemIntroduction == null ? null : systemIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_system_survey
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", systemName=").append(systemName);
        sb.append(", systemAddr=").append(systemAddr);
        sb.append(", systemStatus=").append(systemStatus);
        sb.append(", systemContractor=").append(systemContractor);
        sb.append(", inchargeMan=").append(inchargeMan);
        sb.append(", inchargeTel=").append(inchargeTel);
        sb.append(", managerDept=").append(managerDept);
        sb.append(", managerName=").append(managerName);
        sb.append(", managerTel=").append(managerTel);
        sb.append(", dataStatus=").append(dataStatus);
        sb.append(", systemIntroduction=").append(systemIntroduction);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}