package com.caochf.mapper;

import com.caochf.entity.OdSystemSurvey;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface OdSystemSurveyMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_system_survey
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_system_survey
     *
     * @mbg.generated
     */
    int insert(OdSystemSurvey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_system_survey
     *
     * @mbg.generated
     */
    OdSystemSurvey selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_system_survey
     *
     * @mbg.generated
     */
    List<OdSystemSurvey> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_system_survey
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OdSystemSurvey record);
}