spring:
  thymeleaf:
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    cache: false
    mode: HTML
    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mytest?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1
  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static
server:
  port: 8182
#  servlet:
#    path: /thymeleaf

